[phases.setup]
nixPkgs = ["python3"]
aptPkgs = ["swaks", "curl", "wget", "perl", "python3-pip"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 test.py"
